#!/bin/sh
# This adds color to a few basic commands
alias grep='grep --color=auto'
alias ls="ls --color=auto"
alias diff='diff --color=auto'

# This is adds colos to 'man' by hacking less.
man() {
    LESS_TERMCAP_md=$'\e[01;31m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_se=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[01;44;33m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[01;32m' \
    command man "$@"
}
