#!/bin/sh

# DEFAULTS
# Commands replaced with themselves + various options.
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ls='ls -Fh --group-directories-first --color'
alias free='free -ht'
alias du='du -h'
alias df='df -h'
alias mpv='mpv --audio-display=no'
# Replace vi/vim with nvim
alias vi='nvim'
alias vim='nvim'
alias oldvim='/usr/bin/vim'
# Replace cat with plain unpaged bat,
# which is basically cat with syntax highlighting
alias cat='bat --style plain --paging never'
alias oldcat='/usr/bin/cat'
# Commands replaced with themselves + sudo
alias ip='sudo ip'
alias netctl='sudo netctl'

# ALIASES
# Simple aliases for various commands
alias ytdl="youtube-dl"
alias svtdl="svtplay-dl"
alias ll="ls -l"
alias la="ls -a"
alias lla="ls -la"
alias l1="ls -1"
alias cpdir="cp -rfv"
# A little more complicated aliases
alias weather="curl wttr.in/Gothenburg\?0Q"
alias rightnow="date +\(%a\)\ %d\ %b\ %H:%M"
alias termbin="nc termbin.com 9999"
alias systemage="head -n1 /var/log/pacman.log | awk '{ print \$1, \$2 }'"
alias parch='ping -c 3 archlinux.org'
alias publicip='curl ifconfig.me'
alias demoterm='setopt interactivecomments && export PS1="%B%F{cyan}$ %f%b" && clear'

# SYSTEMD
# SystemD system services
# (enable and disable are already taken)
alias service='sudo systemctl'
alias restart='sudo systemctl restart'
alias start='sudo systemctl start'
alias stop='sudo systemctl stop'
alias status='sudo systemctl status'
# SystemD user services
# Same names as above but with a u at the beginning
alias uservice='systemctl --user'
alias urestart='systemctl restart --user'
alias ustart='systemctl start --user'
alias ustop='systemctl stop --user'
alias ustatus='systemctl status --user'
alias uenable='systemctl enable --user'
alias udisable='systemctl disable --user'

# PACMAN/YAY
# Update packages
alias syyu='yay -Syyu --upgrademenu --combinedupgrade'
alias syu='yay -Syu --upgrademenu --combinedupgrade'
alias upgit="pacman -Qm |
    grep '\-git\|\-hg' |
    awk '{print \$1}' |
    yay -S -"
# Installing/removing packages
alias pmdel="sudo pacman -Rs"
alias pmadd="sudo pacman -S"
# Checking/listing
alias pmall='pacman -Qe'
alias pmnot='pacman -Qdtq'
alias aur='pacman -Qm'
alias pmaur='pacman -Qm'
alias pmgit="pacman -Qm | grep '\-git\|\-hg' | awk '{print \$1}'"
alias pmlook="pacman -Qi"

# DUMB EXITS
# Sorry...
alias quit='exit'; alias q='exit'; alias :q='exit'
alias :q!='exit'; alias wq='exit'; alias :wq='exit'
alias :wq!='exit'
