#!/bin/sh
# GUI applications
alias spotify="spotify --force-device-scale-factor=2 & disown"
alias ffwayland="GDK_BACKEND=wayland firefox & disown"

# I get confused sometimes....
# and I enjoy adding support for dumb stuff.
alias quit='exit'
alias q='exit'
alias :q='exit'
alias :q!='exit'
alias wq='exit'
alias :wq='exit'
alias :wq!='exit'

# Colorisation and autosettings
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ls='ls -Fh --group-directories-first --color'
alias free='free -ht'
alias du='du -h'
alias vi='vim'

# Auto sudo
alias ip='sudo ip'
alias systemctl='sudo systemctl'

# System maintenance
alias parch='ping archlinux.org'
# List or look up pacman/aur packages
alias aur='pacman -Qm'
alias pmaur='pacman -Qm'
alias pmall='pacman -Qe'
alias pmgit="pacman -Qm | grep '\-git\|\-hg' | awk '{print \$1}'"
alias pmnot='pacman -Qdtq'
alias pmlook="pacman -Qi"
# Install or update pacman/aur packages
alias syu='yay -Syu'
alias pmsyu='yay -Syu'
alias upsway="yay -S wlroots-git sway-git swayidle-git"
alias upgit="pacman -Qm | grep '\-git\|\-hg' | grep -v 'sway\|wlroots' | awk '{print \$1}' | yay -S -"
alias pmdel="sudo pacman -R"
alias pmadd="sudo pacman -S"
