#!/bin/sh
# GUI applications
alias spotify="spotify --force-device-scale-factor=2 & disown"
alias firefox="GDK_BACKEND=wayland firefox & disown"

# Keeping it just in case, but shouldn't be needed anymore
# alias sway="export XKB_DEFAULT_LAYOUT=se; export XKB_DEFAULT_VARIANT=dvorak_a5; export XKB_DEFAULT_MODEL=pc105; sway"

# I get confused sometimes....
# and I enjoy adding support for dumb stuff.
alias quit='exit'
alias q='exit'
alias :q='exit'
alias :q!='exit'
alias wq='exit'
alias :wq='exit'
alias :wq!='exit'

# Colorisation
alias ls='ls -F --group-directories-first --color'
alias grep='grep --color=auto'
alias diff='diff --color=auto'

# Auto sudo
alias ip='sudo ip'
alias pacman='sudo pacman'
alias systemctl='sudo systemctl'

# System maintenance
alias parch='ping archlinux.org'
alias free='free -ht'

# YAY-stuff
alias syu='yay -Syu'
alias pmsyu='yay -Syu'
alias upsway="yay -S wlroots-git sway-git swayidle-git slurp-git grim-git"

# PACMAN-stuff
alias aur='pacman -Qm'
alias pmaur='pacman -Qm'
alias pmall='pacman -Qe'
alias pmgit='pacman -Qm | grep "git\|hg"'
alias pmnot='pacman -Qdtq'
alias pmlook="pacman -Qi"
alias pmdel="sudo pacman -R"
alias pmadd="sudo pacman -S"
