#!/usr/bin/env python
# Hashpling for syntax highlighting.

################
### MESSAGES ###
################
# Original theme was white text on colored background.
# New one is colored text on dark background.
c.colors.messages.info.bg                     = nord['frost-2']
c.colors.messages.info.fg                     = nord['snow-2']
c.colors.messages.error.bg                    = nord['red']
c.colors.messages.error.fg                    = nord['snow-2']
c.colors.messages.warning.bg                  = nord['orange']
c.colors.messages.warning.fg                  = nord['snow-2']
