#!/bin/sh
# SHORTCUTS
alias cwh="cd ~/code/codewars/haskell"
alias cwj="cd ~/code/codewars/java"
alias cwjs="cd ~/code/codewars/js"
alias cwp="cd ~/code/codewars/python"
alias cwr="cd ~/code/codewars/ruby"
alias cdh="cd ~/code/haskbook"
alias xswapescape="setxkbmap \
    -layout se,se \
    -variant dvorak_a5,basic \
    -option caps:swapescape,compose:rctrl,grp:alt_caps_toggle"
alias sway="env XDG_CURRENT_DESKTOP=sway sway"
alias swaybar_ip="pkill -RTMIN+9 i3blocks"

# DEFAULTS
# Commands replaced with themselves + various options.
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ls='ls -Fh --group-directories-first --color'
alias free='free -ht'
alias du='du -h'
alias df='df -h'
alias mpv='mpv --audio-display=no'
# Replace vi/vim with nvim
alias vi='nvim'
alias vim='nvim'
alias oldvim='/usr/bin/vim'
alias bat='bat --style plain --paging never'
# Commands replaced with themselves + sudo
alias ip='sudo ip'
alias netctl='sudo netctl'

# ALIASES
# Simple aliases for various commands
alias ytdl="youtube-dl"
alias pldl="youtube-dl -o '~/video/ytdl/%(uploader)s_%(playlist)s/%(playlist_index)s_%(title)s.%(ext)s'"
alias svtdl="svtplay-dl"
alias ll="ls -l"
alias la="ls -a"
alias lla="ls -la"
alias l1="ls -1"
alias cpdir="cp -rfv"
# Lazy gitting
alias gits="git status"
alias gita="git add"
alias gitb="git branch"
alias gitc="git commit -m"
alias gitl="git log --oneline"
alias gitp="git push"
alias gitd="git diff"
alias chko="git checkout"
# A little more complicated aliases
alias weather="curl wttr.in/Gothenburg\?0Q"
alias rightnow="date +\(%a\)\ %d\ %b\ %H:%M"
alias termbin="nc termbin.com 9999"
alias systemage="head -n1 /var/log/pacman.log | awk '{ print \$1, \$2 }'"
alias parch='ping -c 3 archlinux.org'
alias publicip='curl ifconfig.me'
alias demoterm='setopt interactivecomments && export PS1="%B%F{cyan}$ %f%b" && clear'

# SYSTEMD
# SystemD system services
# (enable and disable are already taken)
alias service='sudo systemctl'
alias restart='sudo systemctl restart'
alias start='sudo systemctl start'
alias stop='sudo systemctl stop'
alias status='sudo systemctl status'
# SystemD user services
# Same names as above but with a u at the beginning
alias uservice='systemctl --user'
alias urestart='systemctl restart --user'
alias ustart='systemctl start --user'
alias ustop='systemctl stop --user'
alias ustatus='systemctl status --user'
alias uenable='systemctl enable --user'
alias udisable='systemctl disable --user'
alias ujournal='journalctl --user -u'

# DUMB EXITS
# Sorry...
alias quit='exit'; alias q='exit'; alias :q='exit'
