#!/bin/sh
# SHORTCUTS
alias update-battery="~/.config/i3blocks/battery && pkill -RTMIN+9 i3blocks"
alias dcdu="docker-compose down; docker-compose up"
alias ncp="ncpamixer"
alias tf="terraform"
alias tf-fmt="terraform fmt -recursive ."

# ADD OPTIONS
# Commands replaced with themselves + various options.
alias bat="bat --style plain --paging never"
alias df="df -h"
alias diff="diff --color=auto"
alias du="du -h"
alias exa="exa --group-directories-first --git --time-style long-iso"
alias free="free -ht"
alias grep="grep --color=auto"
alias ls="ls -Fh --group-directories-first --color"
alias mpv="mpv --audio-display=no"
alias sway="sway-init"
alias tmux="tmux -f '$XDG_CONFIG_HOME/tmux/tmux.conf'"
# Auto-sudo (commands replaced with sudo + themselves)
alias ip="sudo ip"
alias netctl="sudo netctl"
alias wifi="sudo wifi-menu"
alias nixos-rebuild="sudo nixos-rebuild"

# ALIASES
# Simple aliases for various commands
alias ytdl="yt-dlp"
alias pldl="yt-dlp -o '~/video/ytdl/%(uploader)s_%(playlist)s/%(playlist_index)s_%(title)s.%(ext)s'"
alias svtdl="svtplay-dl"
alias ll="ls -l"
alias l1="ls -1"
alias e="exa"
alias el="exa -l"
alias e1="exa -1"
alias cpdir="cp -rfv"
alias lintkt="./gradlew lintKotlin"
alias formatkt="./gradlew formatKotlin"

# Lazy gitting
alias gits="git status"
alias gita="git add"
alias gitb="git branch"
alias gitc="git commit -m"
alias gitl="git log --oneline"
alias gitp="git push"
alias gitpp="git push && { git push github || git push codeberg; }"
alias gitd="git diff"
alias gitr="git rebase"
alias gco="git checkout"
alias git-message="git show -s --format=%B" # followed by commit hash/HEAD

# Slightly more complicated aliases
alias termbin="nc termbin.com 9999"
alias systemage="head -n1 /var/log/pacman.log | awk '{ print \$1, \$2 }'"
alias parch="ping -c 3 archlinux.org"
alias pnine="ping -c 3 9.9.9.9"
alias publicip="curl ifconfig.me"
alias demoterm="setopt interactivecomments && export PS1=\"%B%F{cyan}$ %f%b\" && clear"
alias xswapescape="setxkbmap \
    -layout se,se \
    -variant dvorak_a5,basic \
    -option caps:swapescape,compose:rctrl,grp:alt_caps_toggle"
alias swaybar_ip="pkill -RTMIN+9 i3blocks"
alias newsboat-refresh="pgrep i3blocks > /dev/null && pkill -RTMIN+13 i3blocks || newsboat -x reload"
alias brightness-max="cat /sys/class/backlight/intel_backlight/max_brightness | sudo tee /sys/class/backlight/intel_backlight/brightness"
alias brightness-mid="echo 3000 | sudo tee /sys/class/backlight/intel_backlight/brightness"
alias brightness-low="echo 500 | sudo tee /sys/class/backlight/intel_backlight/brightness"
alias brightness-min="echo 1 | sudo tee /sys/class/backlight/intel_backlight/brightness"

# SYSTEMD
alias systemctl="sudo systemctl"
alias systemctlu="systemctl --user"
alias journalctlu="journalctl --user"

# DUMB EXITS
alias q="exit"
