#!/usr/bin/env zsh
autoload -U compinit && compinit
autoload -U +X bashcompinit && bashcompinit

zstyle ':completion:*' menu select
zmodload zsh/complist

# Load dotfile completions
fpath=("$ZDOTDIR/completions" $fpath)
[ -d "$ZDOTDIR/completions.local" ] \
  && fpath=("$ZDOTDIR/completions.local" $fpath)

# Scaleway CLI autocomplete
if [[ -x $(which scw) ]]; then
  eval "$(scw autocomplete script shell=zsh)"
fi

# Terraform autocomplete
if [[ -x $(which terraform) ]]; then
  complete -o nospace -C /usr/bin/terraform terraform
fi

# Git Town autocomplete
if [[ -x $(which git-town) ]]; then
  source <(git-town completions zsh)
fi
