#!/usr/bin/env zsh
function init-pyenv {
  if [[ -d "${PYENV_ROOT}" ]] ; then
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
  fi
}

function init-rbenv {
  if [[ -d "${RBENV_ROOT}" ]] ; then
    export PATH="$RBENV_ROOT/bin:$PATH"
    export PATH="$RBENV_ROOT/plugins/ruby-build/bin:$PATH"
    eval "$(rbenv init -)"
  fi
}

function init-nvm {
  if [[ -e "/usr/share/nvm/init-nvm.sh" ]] ; then
    unset npm_config_prefix
    source /usr/share/nvm/init-nvm.sh
  fi
}

function init-heroku {
  HEROKU_AC_ZSH_SETUP_PATH=/home/terminal/.cache/heroku/autocomplete/zsh_setup
  if [[ -f $HEROKU_AC_ZSH_SETUP_PATH ]] ; then
    source $HEROKU_AC_ZSH_SETUP_PATH
  fi
}

function init-platformio {
  eval "$(_PIO_COMPLETE=zsh_source pio)"
}

export PNPM_HOME="/home/terminal/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
