#!/bin/sh
alias weather="curl wttr.in/Gothenburg\?0Q"

################
### DEFAULTS ###
################
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ls='ls -Fh --group-directories-first --color'
alias free='free -ht'
alias du='du -h'
alias df='df -h'
alias vi='vim'
alias mpv='mpv --audio-display=no'
alias neofetch='neofetch \
--disable icons theme resolution term_font model \
--uptime_shorthand on --shell_version off \
--memory_percent on --speed_shorthand on \
--os_arch off --shell_path on'

#################
### AUTO SUDO ###
#################
alias ip='sudo ip'
alias systemctl='sudo systemctl'
alias netctl='sudo netctl'

##########################
### SYSTEM MAINTENANCE ###
##########################
# Various
alias systemage="head -n1 /var/log/pacman.log | awk '{ print \$1, \$2 }'"
alias parch='ping -c 3 archlinux.org'

# Updating
alias syyu='yay -Syyu --upgrademenu --combinedupgrade'
alias syu='yay -Syu --upgrademenu --combinedupgrade'
alias upgit="pacman -Qm |
    grep '\-git\|\-hg' |
    awk '{print \$1}' |
    yay -S -"

# Installing/removing packages
alias pmdel="sudo pacman -R"
alias pmadd="sudo pacman -S"

# Checking/listing
alias pmall='pacman -Qe'
alias pmnot='pacman -Qdtq'
alias aur='pacman -Qm'
alias pmaur='pacman -Qm'
alias pmgit="pacman -Qm | grep '\-git\|\-hg' | awk '{print \$1}'"
alias pmlook="pacman -Qi"

###################
### DUMB EXITS ###
###################
alias quit='exit'; alias q='exit'; alias :q='exit'
alias :q!='exit'; alias wq='exit'; alias :wq='exit'
alias :wq!='exit'
