#!/bin/sh
# OC
alias weather="curl wttr.in/Gothenburg\?0Q"

# GUI applications
alias ffwayland="GDK_BACKEND=wayland firefox & disown"

# I get confused sometimes....
# and I enjoy adding support for dumb stuff.
alias quit='exit'
alias q='exit'
alias :q='exit'
alias :q!='exit'
alias wq='exit'
alias :wq='exit'
alias :wq!='exit'

# Colorisation and autosettings
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ls='ls -Fh --group-directories-first --color'
alias free='free -ht'
alias du='du -h'
alias df='df -h'
alias vi='vim'
alias neofetch='neofetch --disable icons theme resolution term_font model --uptime_shorthand on --shell_version off --memory_percent on --speed_shorthand on --os_arch off --shell_path on'
alias mpv='mpv --audio-display=no'

# Auto sudo
alias ip='sudo ip'
alias systemctl='sudo systemctl'

# System maintenance
alias parch='ping -c 3 archlinux.org'
alias systemage='head -n1 /var/log/pacman.log'
# List or look up pacman/aur packages
alias aur='pacman -Qm'
alias pmaur='pacman -Qm'
alias pmall='pacman -Qe'
alias pmgit="pacman -Qm | grep '\-git\|\-hg' | awk '{print \$1}'"
alias pmnot='pacman -Qdtq'
alias pmlook="pacman -Qi"
# Install or update pacman/aur packages
# alias upsway="yay -S wlroots-git sway-git swayidle-git"
# alias upgit="pacman -Qm | grep '\-git\|\-hg' | grep -v 'sway\|wlroots' | awk '{print \$1}' | yay -S -"
alias upgit="pacman -Qm | grep '\-git\|\-hg' | awk '{print \$1}' | yay -S -"
alias syyu='yay -Syyu --upgrademenu --combinedupgrade'
alias syu='yay -Syu --upgrademenu --combinedupgrade'
alias pmsyu='yay -Syu --upgrademenu --combinedupgrade'
alias pmsyyu='yay -Syyu --upgrademenu --combinedupgrade'
alias pmdel="sudo pacman -R"
alias pmadd="sudo pacman -S"
