#!/bin/sh
BAT="/sys/class/power_supply/BAT0"
FULL=$( cat ${BAT}/charge_full )
NOW=$( cat ${BAT}/charge_now )
CHARGE=$(( 100 * NOW / FULL ))

# Status can be "Charging", "Discharging", "Full" or "Unknown".
# If charging or full a powersupply must be connected.
STATUS=$( sed '2!d;s/.*=//' ${BAT}/uevent )

if [ "$STATUS" = "Full" ]; then
    SYMBOL=" "
    CHARGE="FULL"
fi

if [ "$STATUS" = "Charging" ]; then
    SYMBOL="  "
    CHARGE="${CHARGE}%"
fi

if [ "$STATUS" = "Discharging" ]; then
    if [ "$CHARGE" -le 10 ]; then
        SYMBOL="  "
        echo "${SYMBOL}${CHARGE}%"
        exit 33

    elif [ "$CHARGE" -le 25 ]; then
        SYMBOL="  "
        echo "${SYMBOL}${CHARGE}%"
        exit 33

    elif [ "$CHARGE" -le 50 ]; then
        SYMBOL="  "

    elif [ "$CHARGE" -le 75 ]; then
        SYMBOL="  "

    else
        SYMBOL=" "
    fi
    CHARGE="${CHARGE}%"
fi

echo "${SYMBOL}${CHARGE}"
echo "${SYMBOL}${CHARGE}"
