#!/usr/bin/env ruby
# Output the current time in decimal time with 1 normal second accuracy.
require "date"

decimalHourSeconds = 8640
decimalMinuteSeconds = 86.4

secondsPassed = DateTime.now.to_time.to_i - Date.today.to_time.to_i
decimalHour, secondsPassed = secondsPassed.divmod(decimalHourSeconds)
decimalMinute = (secondsPassed / decimalMinuteSeconds).to_i

puts "#{decimalHour}:#{decimalMinute}"
puts "#{decimalHour}:#{decimalMinute}"
