#!/bin/sh
interfaces=("eth0" "eth1" "wlan0")

function get_ip() {
  ip addr show "$1" |
    awk '/inet / {split($2, a, "/"); print a[1]; exit}'
}

for interface in "${interfaces[@]}"; do
  ip_address=$(get_ip "$interface")
  if [ -n "$ip_address" ]; then
    echo $ip_address
    exit 0
  fi
done

echo "IP unknown"

