#!/bin/sh
sleep 0.05 # Too fast!!!
getsink() {
    pacmd list-sinks |
        awk '/index:/{i++} /* index:/{print i; exit}'
}

getvolume() {
    pacmd list-sinks |
        awk '/^\svolume:/{i++} i=='"$(getsink)"'{print $5; exit}' |
        cut -d'%' -f1 # remove trailing % sign
}

getmute() {
    pacmd list-sinks |
        awk '/^\smuted:/{i++} i=='"$(getsink)"'{print $2; exit}'
}

VOL=$(getvolume)
[ "$(getmute)" = "yes" ] && echo .MUTE && return
[ "$VOL" -ge 75 ] && echo " $VOL" && return
[ "$VOL" -ge 25 ] && echo " $VOL" && return
echo  $VOL
